"""
Django settings for finbit_backend project.

Generated by 'django-admin startproject' using Django 4.2.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

try:
    from decouple import AutoConfig
except ImportError:  # pragma: no cover
    AutoConfig = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = AutoConfig(search_path=str(BASE_DIR)) if AutoConfig else None


def _env(name: str, default: str = '') -> str:
    if env is not None:
        return env(name, default=default)
    value = os.getenv(name)
    if value is None:
        return default
    return value


# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable, fallback to a secure random key for development
SECRET_KEY = _env(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-key-change-this-in-production-12345abcdefg'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env('DJANGO_DEBUG', 'True').lower() == 'true'


def _env_bool(name: str, default: bool = False) -> bool:
    value = _env(name, None)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_csv(name: str, default: str = ''):
    raw = _env(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


def _normalized_ngrok_url() -> str:
    raw_url = _env('NGROK_URL', '').strip()
    if not raw_url:
        return ''
    if not raw_url.startswith(('http://', 'https://')):
        raw_url = f'https://{raw_url}'
    return raw_url.rstrip('/')


NGROK_URL = _normalized_ngrok_url()
NGROK_HOST = urlparse(NGROK_URL).netloc if NGROK_URL else ''

allowed_hosts = _env_csv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost')
if NGROK_HOST and NGROK_HOST not in allowed_hosts:
    allowed_hosts.append(NGROK_HOST)

if DEBUG:
    # Keep dev resilient: allow local interfaces without exposing production configs.
    for dev_host in ('0.0.0.0', '::1'):
        if dev_host not in allowed_hosts:
            allowed_hosts.append(dev_host)

    # Mobile and emulator clients usually call the API via LAN IP (for example 10.x/192.168.x).
    # Allow all hosts only in DEBUG to avoid DisallowedHost during local development.
    if '*' not in allowed_hosts:
        allowed_hosts.append('*')

ALLOWED_HOSTS = allowed_hosts or ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    
    # Local apps
    'users',
    'transactions',
    'receipts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'finbit_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'finbit_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": _env("DB_NAME", "fin_bit"),
        "USER": _env("DB_USER", "root"),
        "PASSWORD": _env("DB_PASSWORD", ""),
        "HOST": _env("DB_HOST", "127.0.0.1"),
        "PORT": _env("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}

# Keep Django auth tied to the existing custom users table.
AUTH_USER_MODEL = 'users.User'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.UserTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# CORS / CSRF Configuration
default_cors_origins = (
    'http://localhost:19000,http://localhost:19001,http://localhost:8081,'
    'http://127.0.0.1:19000,http://127.0.0.1:8081,http://10.0.2.2:19000,http://10.0.2.2:8081'
)
CORS_ALLOWED_ORIGINS = _env_csv('CORS_ALLOWED_ORIGINS', default_cors_origins)
if NGROK_URL and NGROK_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(NGROK_URL)

CORS_ALLOW_ALL_ORIGINS = _env_bool('CORS_ALLOW_ALL_ORIGINS', False)

# Expo dev URLs vary and are safe to allow in local development.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^exp://.*$',
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = _env_csv('CSRF_TRUSTED_ORIGINS', '')
if NGROK_URL and NGROK_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(NGROK_URL)

# Log configuration for debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
