# Generated by Django 4.2 on 2026-03-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_receiptcapture_transaction_and_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptcapture',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('bill', 'Bill'), ('transport', 'Transport'), ('shopping', 'Shopping'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
