# Generated by Django 4.2.11 on 2026-03-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('sms', 'SMS'), ('scanner', 'Scanner')], default='manual', max_length=20),
        ),
    ]
