# Generated by Django 4.2.11 on 2026-03-24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sms',
            name='sender',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='sms',
            name='sms_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
