# Generated by Django 4.2 on 2026-03-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_categorybudget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
